export const adirondacks2025 = [
  { alt: 'Mountain Peak', src: 'https://i.imgur.com/9dbpXidh.jpg' },
  { alt: 'Night Sky', src: 'https://i.imgur.com/EuZ9XEuh.jpg' },
  { alt: 'Babbling brook', src: 'https://i.imgur.com/pSY0fwOh.jpg' },
  { alt: 'Mountain Range', src: 'https://i.imgur.com/iOpbW0fh.jpg' },
  { alt: 'Mountain Range', src: 'https://i.imgur.com/xjtvk7th.jpg' },
  { alt: 'Night Sky', src: 'https://i.imgur.com/5AdZqUOh.jpg' },
  { alt: 'Mountain Range', src: 'https://i.imgur.com/f1DJjmZh.jpg' },
  { alt: 'Mountain Range', src: 'https://i.imgur.com/GkQwQZrh.jpg' },
  { alt: 'Mountain Range', src: 'https://i.imgur.com/n8oXwoOh.jpg' },
  { alt: 'Mountain Range', src: 'https://i.imgur.com/KToTV0uh.jpg' },
  { alt: 'Cairn', src: 'https://i.imgur.com/UkXx6E8h.jpg' },
  { alt: 'Mountain Range', src: 'https://i.imgur.com/a4QW7CGh.jpg' },
  { alt: 'Mountain Range', src: 'https://i.imgur.com/gEUV2qNh.jpg' },
  { alt: 'Mountain Range', src: 'https://i.imgur.com/qslXcWyh.jpg' },
  { alt: 'Night Sky', src: 'https://i.imgur.com/UFFEX41h.jpg' },
  { alt: 'Mountain Range', src: 'https://i.imgur.com/Ye0iJqah.jpg' },
  { alt: 'Mountain Range', src: 'https://i.imgur.com/MrV4sRqh.jpg' },
  { alt: 'Night Sky', src: 'https://i.imgur.com/EUaGBJYh.jpg' },
  { alt: 'Mountain Range', src: 'https://i.imgur.com/3T7PKtUh.jpg' },
  { alt: 'Mountain Range', src: 'https://i.imgur.com/cFQOnBWh.jpg' },
  { alt: 'Mountain Peak', src: 'https://i.imgur.com/CMq0qSRh.jpg' },
  { alt: 'Night Sky', src: 'https://i.imgur.com/xd1hkMrh.jpg' },
  { alt: 'Mountain Range', src: 'https://i.imgur.com/vCNm0k0h.jpg' },
  { alt: 'Night Sky', src: 'https://i.imgur.com/OzTzG8kh.jpg' },
  { alt: 'Mountain Range', src: 'https://i.imgur.com/X0xdsx0h.jpg' },
  { alt: 'Mountain Range', src: 'https://i.imgur.com/CMRxEzdh.jpg' },
  { alt: 'Mountain Range', src: 'https://i.imgur.com/QSx9mGCh.jpg' },
  { alt: 'Mountain Range', src: 'https://i.imgur.com/8RuZLEJh.jpg' },
  { alt: 'Night Sky', src: 'https://i.imgur.com/7twR6MKh.jpg' },
]

export const alaska2018 = [
  { alt: 'Field with mountain peak in back', src: 'https://i.imgur.com/yol64gjh.jpg' },
  { alt: 'Field with mountain peak in back', src: 'https://i.imgur.com/oIGn8poh.jpg' },
  { alt: 'Field with mountain peak in back', src: 'https://i.imgur.com/4MBP1gXh.jpg' },
  { alt: 'Field with mountain peak in back', src: 'https://i.imgur.com/TGBBJlQh.jpg' },
  { alt: 'Mountain peak', src: 'https://i.imgur.com/yWWw9g0h.jpg' },
  { alt: 'Mountain peak', src: 'https://i.imgur.com/ZAtohHeh.jpg' },
  { alt: 'Mountain peak', src: 'https://i.imgur.com/sqG9mCVh.jpg' },
  { alt: 'Mountain peak', src: 'https://i.imgur.com/HscGAFyh.jpg' },
  { alt: 'Mountain peak', src: 'https://i.imgur.com/rtKswirh.jpg' },
  { alt: 'Purple flowers with mountain in back', src: 'https://i.imgur.com/Owywbv3h.jpg' },
  { alt: 'Purple flowers with mountain in back', src: 'https://i.imgur.com/lQfftxah.jpg' },
  { alt: 'Purple flowers with mountain in back', src: 'https://i.imgur.com/RNTieYrh.jpg' },
  { alt: 'Mountain peal through windshield', src: 'https://i.imgur.com/8CbhdQjh.jpg' },
  { alt: 'Sunset on mountain ridge', src: 'https://i.imgur.com/uJdzzpih.jpg' },
  { alt: 'Sunset on water tank', src: 'https://i.imgur.com/6sQFLNHh.jpg' },
  { alt: 'Valley with mountains in back', src: 'https://i.imgur.com/i4aCXmKh.jpg' },
  { alt: 'Sunset over anchorage', src: 'https://i.imgur.com/VRkV04Oh.jpg' },
  { alt: 'Flower field in front of mountain', src: 'https://i.imgur.com/0UWgIi3h.jpg' },
];

export const alaska2020 = [
  { alt: '', src: 'https://imgur.com/iTVZnoZh.jpg' },
  { alt: '', src: 'https://imgur.com/oKa75pHh.jpg' },
  { alt: '', src: 'https://imgur.com/v8DzS1Eh.jpg' },
  { alt: '', src: 'https://imgur.com/BjkpdYph.jpg' },
  { alt: '', src: 'https://imgur.com/QmL9PmXh.jpg' },
  { alt: '', src: 'https://imgur.com/jwFscAAh.jpg' },
  { alt: '', src: 'https://imgur.com/vFTdYMlh.jpg' },
  { alt: '', src: 'https://imgur.com/gmWBSAoh.jpg' },
  { alt: '', src: 'https://imgur.com/chtgUzBh.jpg' },
  { alt: '', src: 'https://imgur.com/UXNmgMNh.jpg' },
  { alt: '', src: 'https://imgur.com/tgUbs9th.jpg' },
  { alt: '', src: 'https://imgur.com/vV9CwGYh.jpg' },
  { alt: '', src: 'https://imgur.com/FfDcmFih.jpg' },
  { alt: '', src: 'https://imgur.com/Nc0ui2ch.jpg' },
  { alt: '', src: 'https://imgur.com/hgJC2D2h.jpg' },
  { alt: '', src: 'https://imgur.com/nbmtSRFh.jpg' },
  { alt: '', src: 'https://imgur.com/XUukZkth.jpg' },
  { alt: '', src: 'https://imgur.com/in1F593h.jpg' },
];

export const malabar2019 = [
  { alt: 'Rock formation', src: 'https://i.imgur.com/i6v6J0wh.jpg' },
  { alt: 'The pacific ocean skyline', src: 'https://i.imgur.com/3QzBHOWh.jpg' },
  { alt: 'Sand stone formation', src: 'https://i.imgur.com/lilY8oBh.jpg' },
  { alt: 'Rocky beach cliff', src: 'https://i.imgur.com/HpuCSHoh.jpg' },
  { alt: 'Rock with a lot of holes', src: 'https://i.imgur.com/GV528pkh.jpg' },
  { alt: 'Rock cliff', src: 'https://i.imgur.com/fDnaiDhh.jpg' },
  { alt: 'Rock cliff', src: 'https://i.imgur.com/zQ6fMGRh.jpg' },
  { alt: 'Skull graffiti', src: 'https://i.imgur.com/9D9dFFSh.jpg' },
  { alt: 'Waves crashing on rock cliff', src: 'https://i.imgur.com/XUh1o8Jh.jpg' },
  { alt: 'Rocky beach cliff', src: 'https://i.imgur.com/4PYNliTh.jpg' },
  { alt: 'Rocky formation', src: 'https://i.imgur.com/zhe5l5vh.jpg' },
];

export const mammoth2020 = [
  { alt: '', src: 'https://imgur.com/1utq2yqh.jpg' },
  { alt: '', src: 'https://imgur.com/T7MjBdsh.jpg' },
  { alt: '', src: 'https://imgur.com/alDWxFVh.jpg' },
  { alt: '', src: 'https://imgur.com/gIbfArqh.jpg' },
  { alt: '', src: 'https://imgur.com/L2YfnW6h.jpg' },
  { alt: '', src: 'https://imgur.com/BwzwTJah.jpg' },
  { alt: '', src: 'https://imgur.com/AVnzEAHh.jpg' },
  { alt: '', src: 'https://imgur.com/0CrmUoBh.jpg' },
  { alt: '', src: 'https://imgur.com/aBBvxrJh.jpg' },
  { alt: '', src: 'https://imgur.com/rQATyR8h.jpg' },
  { alt: '', src: 'https://imgur.com/s4abVRKh.jpg' },
  { alt: '', src: 'https://imgur.com/WeZBTrmh.jpg' },
  { alt: '', src: 'https://imgur.com/z6bjSavh.jpg' },
  { alt: '', src: 'https://imgur.com/UQujKmfh.jpg' },
  { alt: '', src: 'https://imgur.com/hB2PoLXh.jpg' },
  { alt: '', src: 'https://imgur.com/wGR0feTh.jpg' },
  { alt: '', src: 'https://imgur.com/kUG6fphh.jpg' },
  { alt: '', src: 'https://imgur.com/3ATEcZrh.jpg' },
  { alt: '', src: 'https://imgur.com/OLuZ5uhh.jpg' },
  { alt: '', src: 'https://imgur.com/kly5MHvh.jpg' },
  { alt: '', src: 'https://imgur.com/Pjys7TMh.jpg' },
  { alt: '', src: 'https://imgur.com/uJnV23nh.jpg' },
  { alt: '', src: 'https://imgur.com/1yp51Pth.jpg' },
  { alt: '', src: 'https://imgur.com/g7HvCpEh.jpg' },
  { alt: '', src: 'https://imgur.com/s6tBbE3h.jpg' },
  { alt: '', src: 'https://imgur.com/rH3Xr3Lh.jpg' },
  { alt: '', src: 'https://imgur.com/FUowoImh.jpg' },
  { alt: '', src: 'https://imgur.com/8FYswirh.jpg' },
  { alt: '', src: 'https://imgur.com/Ey79SR4h.jpg' },
  { alt: '', src: 'https://imgur.com/OFKoE0gh.jpg' },
  { alt: '', src: 'https://imgur.com/9oTpx67h.jpg' },
  { alt: '', src: 'https://imgur.com/aBlqf1bh.jpg' },
  { alt: '', src: 'https://imgur.com/VAzKPVTh.jpg' },
  { alt: '', src: 'https://imgur.com/82YBjlhh.jpg' },
  { alt: '', src: 'https://imgur.com/zk0fPjgh.jpg' },
  { alt: '', src: 'https://imgur.com/XtxSQ7Lh.jpg' },
];

export const roadtrip2018 = [
  { alt: 'Cloudy golden gate bridge', src: 'https://i.imgur.com/TIOUR0jh.jpg' },
  { alt: 'Golden gate bridge', src: 'https://i.imgur.com/F6faSNHh.jpg' },
  { alt: 'Welcome to oregon sign', src: 'https://i.imgur.com/r6M4uBSh.jpg' },
  { alt: 'No skateboarding sign', src: 'https://i.imgur.com/D51aCZYh.jpg' },
  { alt: 'Mount Rushmore', src: 'https://i.imgur.com/Oh3EccTh.jpg' },
  { alt: 'Smoke filled woods', src: 'https://i.imgur.com/P1sjmZGh.jpg' },
  { alt: 'Tree with smoke behind', src: 'https://i.imgur.com/iDD2jZRh.jpg' },
  { alt: 'Rocky beach shore', src: 'https://i.imgur.com/tkF9Tioh.jpg' },
  { alt: 'Tree stump', src: 'https://i.imgur.com/gojJX3Ch.jpg' },
  { alt: 'Red flowers on cliff', src: 'https://i.imgur.com/SoZVotmh.jpg' },
  { alt: 'Yellow plant on cliff', src: 'https://i.imgur.com/RAe8QDNh.jpg' },
  { alt: 'Seagull flying over ocean', src: 'https://i.imgur.com/teUSujUh.jpg' },
  { alt: 'Sandy beach trail', src: 'https://i.imgur.com/GRo0G5Rh.jpg' },
  { alt: 'Rocky river bed', src: 'https://i.imgur.com/2E8xqhch.jpg' },
  { alt: 'Sandy beach trail', src: 'https://i.imgur.com/X4N3X1Jh.jpg' },
  { alt: 'Sandy beach trail', src: 'https://i.imgur.com/rhnKrmJh.jpg' },
  { alt: 'Snow covered mount rainier', src: 'https://i.imgur.com/vLK0bT4h.jpg' },
  { alt: 'Rocky river bed', src: 'https://i.imgur.com/YS97q7jh.jpg' },
  { alt: 'Big redwood tree', src: 'https://i.imgur.com/ZMJ94LXh.jpg' },
  { alt: 'Badlands national park welcome sign', src: 'https://i.imgur.com/EyZ4X0Zh.jpg' },
  { alt: 'Flowers with Mount Rainier in back', src: 'https://i.imgur.com/pcPTuKFh.jpg' },
  { alt: 'Park entrance sign', src: 'https://i.imgur.com/NoRjKlqh.jpg' },
  { alt: 'Elk in field', src: 'https://i.imgur.com/q4H9zcQh.jpg' },
  { alt: 'Elk in field', src: 'https://i.imgur.com/lJU5X3rh.jpg' },
  { alt: 'Blue lake with mountains behind', src: 'https://i.imgur.com/eXJKwYeh.jpg' },
  { alt: 'Rocky beach cliff', src: 'https://i.imgur.com/gqpChVnh.jpg' },
  { alt: 'Paul bunyan statue', src: 'https://i.imgur.com/eK0DSrNh.jpg' },
  { alt: 'Sandy beach trail', src: 'https://i.imgur.com/SD4FZBfh.jpg' },
  { alt: 'Road with trees on either side', src: 'https://i.imgur.com/6qF4n5Oh.jpg' },
  { alt: 'Rocky stone bridge', src: 'https://i.imgur.com/8idmR3Nh.jpg' },
  { alt: 'Snow covered mount rainier', src: 'https://i.imgur.com/rB9gzRmh.jpg' },
  { alt: 'Rocky beach shore', src: 'https://i.imgur.com/l7Hkeaeh.jpg' },
  { alt: 'Blue lake with mountains behind', src: 'https://i.imgur.com/TbxcPLPh.jpg' },
  { alt: 'Snow covered mount rainier', src: 'https://i.imgur.com/09KiGvth.jpg' },
  { alt: 'Snow covered mount rainier', src: 'https://i.imgur.com/z0IqDWHh.jpg' },
  { alt: 'Glacier national park welcome sign', src: 'https://i.imgur.com/SkMfJ2Uh.jpg' },
  { alt: 'Blue lake with mountains behind', src: 'https://i.imgur.com/EIyHck5h.jpg' },
  { alt: 'Blue lake with mountains behind', src: 'https://i.imgur.com/wZElGBrh.jpg' },
  { alt: 'Blue lake with mountains behind', src: 'https://i.imgur.com/ZQLyDULh.jpg' },
  { alt: 'Blue lake with mountains behind', src: 'https://i.imgur.com/GzZWZiih.jpg' },
  { alt: 'Blue lake with mountains behind', src: 'https://i.imgur.com/cUsxi9Ah.jpg' },
  { alt: 'Badlands national park', src: 'https://i.imgur.com/oXTFT6Sh.jpg' },
  { alt: 'Badlands national park', src: 'https://i.imgur.com/CqzDWNqh.jpg' },
  { alt: 'Mountain goat in badlands national park', src: 'https://i.imgur.com/PjoaX88h.jpg' },
  { alt: 'Frog in river', src: 'https://i.imgur.com/7n1k0POh.jpg' },
  { alt: 'Tsunami warning sign', src: 'https://i.imgur.com/P45nT1eh.jpg' },
  { alt: 'Elk in field', src: 'https://i.imgur.com/OUlKrXKh.jpg' },
  { alt: 'Frog in river', src: 'https://i.imgur.com/NVEPX8Ph.jpg' },
];

export const roadtrip2022 = [
  { src: 'https://i.imgur.com/XcN5CEVh.jpg', alt: 'Cloudy golden gate bridge' },
  { src: 'https://i.imgur.com/uCnnyoXh.jpg', alt: 'Golden gate bridge' },
  { src: 'https://i.imgur.com/0XMHXlVh.jpg', alt: 'Welcome to oregon sign' },
  { src: 'https://i.imgur.com/C5F5r4uh.jpg', alt: 'No skateboarding sign' },
  { src: 'https://i.imgur.com/seXglrPh.jpg', alt: 'Mount Rushmore' },
  { src: 'https://i.imgur.com/wQ8OpUWh.jpg', alt: 'Smoke filled woods' },
  { src: 'https://i.imgur.com/RTG597Lh.jpg', alt: 'Tree with smoke behind' },
];

export const summer2017 = [
  { alt: 'Grand Canyon welcome sign', src: 'https://i.imgur.com/2nvi3DRh.jpg' },
  { alt: 'River with cliff in background', src: 'https://i.imgur.com/G5vpNWPh.jpg' },
  { alt: 'Green valley with river running through', src: 'https://i.imgur.com/mAUFQpMh.jpg' },
  { alt: 'Green valley with river running through', src: 'https://i.imgur.com/MOWhyNRh.jpg' },
  { alt: 'Trail on cliff', src: 'https://i.imgur.com/7pvL108h.jpg' },
  { alt: 'Narrow canyon', src: 'https://i.imgur.com/ufycp4Wh.jpg' },
  { alt: 'Grand canyon through tree branches', src: 'https://i.imgur.com/cPQI4ith.jpg' },
  { alt: 'Sunset over cliff', src: 'https://i.imgur.com/6cQpC4Ph.jpg' },
  { alt: 'Zion National Park welcome sign', src: 'https://i.imgur.com/xjBY8fPh.jpg' },
  { alt: 'Zion National Park welcome sign', src: 'https://i.imgur.com/6IGnobLh.jpg' },
  { alt: 'Windy road with rocks behind', src: 'https://i.imgur.com/X4Llw61h.jpg' },
  { alt: 'Valley with river running through', src: 'https://i.imgur.com/gDgFEnNh.jpg' },
  { alt: 'Trail through forest', src: 'https://i.imgur.com/z4lsdnxh.jpg' },
  { alt: 'Trail with mountain in back', src: 'https://i.imgur.com/EH4lv5Ah.jpg' },
  { alt: 'Sun setting on lone mountain peak', src: 'https://i.imgur.com/VB2jFLlh.jpg' },
  { alt: 'Intricate cobweb', src: 'https://i.imgur.com/yjeIJxbh.jpg' },
  { alt: 'Sign on bridge over cliff', src: 'https://i.imgur.com/Yzq3JE1h.jpg' },
  { alt: 'Tree branch with mountain in back', src: 'https://i.imgur.com/oGR1ncFh.jpg' },
  { alt: 'Tree branch with mountain in back', src: 'https://i.imgur.com/dbHVfrth.jpg' },
  { alt: 'Deer in forest', src: 'https://i.imgur.com/6Vc7A9lh.jpg' },
];

export const tetons2021 = [
  { alt: '', src:'https://imgur.com/CBNzG0mh.jpg' },
  { alt: '', src:'https://imgur.com/oJalWGRh.jpg' },
  { alt: '', src:'https://imgur.com/NlSFUMvh.jpg' },
  { alt: '', src:'https://imgur.com/yFMF77Dh.jpg' },
  { alt: '', src:'https://imgur.com/A8d5qBeh.jpg' },
  { alt: '', src:'https://imgur.com/kEL4Mcxh.jpg' },
  { alt: '', src:'https://imgur.com/Wk02uxjh.jpg' },
  { alt: '', src:'https://imgur.com/mziP30Eh.jpg' },
  { alt: '', src:'https://imgur.com/CdOPTe2h.jpg' },
  { alt: '', src:'https://imgur.com/nwns525h.jpg' },
  { alt: '', src:'https://imgur.com/QYF3Ntsh.jpg' },
  { alt: '', src:'https://imgur.com/M7vl6CSh.jpg' },
  { alt: '', src:'https://imgur.com/REc3lBjh.jpg' },
  { alt: '', src:'https://imgur.com/5xPT6Rgh.jpg' },
  { alt: '', src:'https://imgur.com/y50ycqEh.jpg' },
  { alt: '', src:'https://imgur.com/jMEa11bh.jpg' },
  { alt: '', src:'https://imgur.com/xsn6amUh.jpg' },
  { alt: '', src:'https://imgur.com/R6i8eYqh.jpg' },
  { alt: '', src:'https://imgur.com/nsKoO8zh.jpg' },
  { alt: '', src:'https://imgur.com/XplkOcNh.jpg' },
  { alt: '', src:'https://imgur.com/gaG7kz4h.jpg' },
  { alt: '', src:'https://imgur.com/LqYj8Pwh.jpg' },
  { alt: '', src:'https://imgur.com/Nsj0dofh.jpg' },
  { alt: '', src:'https://imgur.com/BZLvEsuh.jpg' },
  { alt: '', src:'https://imgur.com/bM9HOOMh.jpg' },
  { alt: '', src:'https://imgur.com/4jLERhjh.jpg' },
  { alt: '', src:'https://imgur.com/w0OX1kYh.jpg' },
  { alt: '', src:'https://imgur.com/ZpmMweah.jpg' },
  { alt: '', src:'https://imgur.com/cnXdkC6h.jpg' },
  { alt: '', src:'https://imgur.com/7G7ZMcih.jpg' },
  { alt: '', src:'https://imgur.com/QeP0Gmqh.jpg' },
  { alt: '', src:'https://imgur.com/JZ3dvfLh.jpg' },
  { alt: '', src:'https://imgur.com/2Vj6i63h.jpg' },
  { alt: '', src:'https://imgur.com/ZOYGVQhh.jpg' },
  { alt: '', src:'https://imgur.com/4uk0NHLh.jpg' },
  { alt: '', src:'https://imgur.com/Hh78of6h.jpg' },
  { alt: '', src:'https://imgur.com/MsNxiNph.jpg' },
  { alt: '', src:'https://imgur.com/6KmGbxhh.jpg' },
];

export const yellowstone2021 = [
  { alt: '', src: 'https://imgur.com/gK7Se9vh.jpg' },
  { alt: '', src: 'https://imgur.com/AvfHwJyh.jpg' },
  { alt: '', src: 'https://imgur.com/hQW8EDxh.jpg' },
  { alt: '', src: 'https://imgur.com/RIZdcvUh.jpg' },
  { alt: '', src: 'https://imgur.com/4kfQYDKh.jpg' },
  { alt: '', src: 'https://imgur.com/hPs33zZh.jpg' },
  { alt: '', src: 'https://imgur.com/pyXZg9Xh.jpg' },
  { alt: '', src: 'https://imgur.com/rdp3efXh.jpg' },
  { alt: '', src: 'https://imgur.com/zOFxlV3h.jpg' },
  { alt: '', src: 'https://imgur.com/PaZKAozh.jpg' },
  { alt: '', src: 'https://imgur.com/cQAUuDNh.jpg' },
  { alt: '', src: 'https://imgur.com/Gsf3piFh.jpg' },
  { alt: '', src: 'https://imgur.com/3NV7SR2h.jpg' },
  { alt: '', src: 'https://imgur.com/Htb3010h.jpg' },
  { alt: '', src: 'https://imgur.com/uNUojCIh.jpg' },
  { alt: '', src: 'https://imgur.com/95LzaXwh.jpg' },
  { alt: '', src: 'https://imgur.com/3vrtpDAh.jpg' },
  { alt: '', src: 'https://imgur.com/jI3j8GOh.jpg' },
  { alt: '', src: 'https://imgur.com/bP3qnP0h.jpg' },
  { alt: '', src: 'https://imgur.com/e7OfvEnh.jpg' },
  { alt: '', src: 'https://imgur.com/CgKJbZth.jpg' },
  { alt: '', src: 'https://imgur.com/bN1I5aqh.jpg' },
  { alt: '', src: 'https://imgur.com/ND1CC9hh.jpg' },
  { alt: '', src: 'https://imgur.com/D8piZcCh.jpg' },
  { alt: '', src: 'https://imgur.com/e1jm51Gh.jpg' },
  { alt: '', src: 'https://imgur.com/lEpSqiSh.jpg' },
  { alt: '', src: 'https://imgur.com/kP0LMMfh.jpg' },
  { alt: '', src: 'https://imgur.com/FWucYsNh.jpg' },
  { alt: '', src: 'https://imgur.com/M45Wnq3h.jpg' },
  { alt: '', src: 'https://imgur.com/ooWzqhOh.jpg' },
  { alt: '', src: 'https://imgur.com/Wb6KL6wh.jpg' },
  { alt: '', src: 'https://imgur.com/bap5nych.jpg' },
  { alt: '', src: 'https://imgur.com/pbbVLETh.jpg' },
  { alt: '', src: 'https://imgur.com/lM09uBGh.jpg' },
  { alt: '', src: 'https://imgur.com/6oOMd9Oh.jpg' },
  { alt: '', src: '' },
];

export const yosemite2019 = [
  { alt: 'Taft point in yosemite', src: 'https://i.imgur.com/Cywm5adh.jpg' },
  { alt: 'Taft point in yosemite', src: 'https://i.imgur.com/t2Vs2qeh.jpg' },
  { alt: 'Taft point in yosemite', src: 'https://i.imgur.com/ms9FOjuh.jpg' },
  { alt: 'Taft point in yosemite', src: 'https://i.imgur.com/ATdT872h.jpg' },
  { alt: 'Taft point in yosemite', src: 'https://i.imgur.com/VfOvzxJh.jpg' },
  { alt: 'El Capitan in yosemite', src: 'https://i.imgur.com/LoN2gGHh.jpg' },
  { alt: 'El Capitan in yosemite', src: 'https://i.imgur.com/4PuAD8eh.jpg' },
  { alt: 'Taft point sign', src: 'https://i.imgur.com/0LWmDqCh.jpg' },
  { alt: 'El capitan', src: 'https://i.imgur.com/Jo7rB7hh.jpg' },
  { alt: 'Big Waterfall', src: 'https://i.imgur.com/O9DYB36h.jpg' },
  { alt: 'Fissure in a cliff', src: 'https://i.imgur.com/kiQ3CC8h.jpg' },
  { alt: 'Fallen tree in woods', src: 'https://i.imgur.com/hfbu7Ahh.jpg' },
  { alt: 'Yosemite valley', src: 'https://i.imgur.com/z5nZFAdh.jpg' },
  { alt: 'Big Waterfall', src: 'https://i.imgur.com/mVwGTVZh.jpg' },
  { alt: 'Sun shining through trees', src: 'https://i.imgur.com/KHii5Ufh.jpg' },
  { alt: 'Yosemite valley', src: 'https://i.imgur.com/ei1x4Zkh.jpg' },
  { alt: 'Redwood trees', src: 'https://i.imgur.com/FBKUdBgh.jpg' },
  { alt: 'Yosemite valley', src: 'https://i.imgur.com/ei1x4Zkh.jpg' },
  { alt: 'Waterfall in yosemite valley', src: 'https://i.imgur.com/MY0QOQXh.jpg' },
  { alt: 'Yosemite valley', src: 'https://i.imgur.com/S2IlYBbh.jpg' },
];
