// LANDSCAPE

import type { Photograph } from '../../../types';

const alaska2018 = [
  { alt: 'Field with mountain peak in back', src: 'https://i.imgur.com/yol64gjh.jpg' },
  { alt: 'Field with mountain peak in back', src: 'https://i.imgur.com/oIGn8poh.jpg' },
  { alt: 'Field with mountain peak in back', src: 'https://i.imgur.com/4MBP1gXh.jpg' },
  { alt: 'Field with mountain peak in back', src: 'https://i.imgur.com/TGBBJlQh.jpg' },
  { alt: 'Mountain peak', src: 'https://i.imgur.com/yWWw9g0h.jpg' },
  { alt: 'Mountain peak', src: 'https://i.imgur.com/ZAtohHeh.jpg' },
  { alt: 'Mountain peak', src: 'https://i.imgur.com/sqG9mCVh.jpg' },
  { alt: 'Mountain peak', src: 'https://i.imgur.com/HscGAFyh.jpg' },
  { alt: 'Mountain peak', src: 'https://i.imgur.com/rtKswirh.jpg' },
  { alt: 'Purple flowers with mountain in back', src: 'https://i.imgur.com/Owywbv3h.jpg' },
  { alt: 'Purple flowers with mountain in back', src: 'https://i.imgur.com/lQfftxah.jpg' },
  { alt: 'Purple flowers with mountain in back', src: 'https://i.imgur.com/RNTieYrh.jpg' },
  { alt: 'Mountain peal through windshield', src: 'https://i.imgur.com/8CbhdQjh.jpg' },
  { alt: 'Sunset on mountain ridge', src: 'https://i.imgur.com/uJdzzpih.jpg' },
  { alt: 'Sunset on water tank', src: 'https://i.imgur.com/6sQFLNHh.jpg' },
  { alt: 'Valley with mountains in back', src: 'https://i.imgur.com/i4aCXmKh.jpg' },
  { alt: 'Sunset over anchorage', src: 'https://i.imgur.com/VRkV04Oh.jpg' },
  { alt: 'Flower field in front of mountain', src: 'https://i.imgur.com/0UWgIi3h.jpg' },
];

const alaska2020 = [
  { alt: '', src: 'https://imgur.com/iTVZnoZh.jpg' },
  { alt: '', src: 'https://imgur.com/oKa75pHh.jpg' },
  { alt: '', src: 'https://imgur.com/v8DzS1Eh.jpg' },
  { alt: '', src: 'https://imgur.com/BjkpdYph.jpg' },
  { alt: '', src: 'https://imgur.com/QmL9PmXh.jpg' },
  { alt: '', src: 'https://imgur.com/jwFscAAh.jpg' },
  { alt: '', src: 'https://imgur.com/vFTdYMlh.jpg' },
  { alt: '', src: 'https://imgur.com/gmWBSAoh.jpg' },
  { alt: '', src: 'https://imgur.com/chtgUzBh.jpg' },
  { alt: '', src: 'https://imgur.com/UXNmgMNh.jpg' },
  { alt: '', src: 'https://imgur.com/tgUbs9th.jpg' },
  { alt: '', src: 'https://imgur.com/vV9CwGYh.jpg' },
  { alt: '', src: 'https://imgur.com/FfDcmFih.jpg' },
  { alt: '', src: 'https://imgur.com/Nc0ui2ch.jpg' },
  { alt: '', src: 'https://imgur.com/hgJC2D2h.jpg' },
  { alt: '', src: 'https://imgur.com/nbmtSRFh.jpg' },
  { alt: '', src: 'https://imgur.com/XUukZkth.jpg' },
  { alt: '', src: 'https://imgur.com/in1F593h.jpg' },
];

const malabar2019 = [
  { alt: 'Rock formation', src: 'https://i.imgur.com/i6v6J0wh.jpg' },
  { alt: 'The pacific ocean skyline', src: 'https://i.imgur.com/3QzBHOWh.jpg' },
  { alt: 'Sand stone formation', src: 'https://i.imgur.com/lilY8oBh.jpg' },
  { alt: 'Rocky beach cliff', src: 'https://i.imgur.com/HpuCSHoh.jpg' },
  { alt: 'Rock with a lot of holes', src: 'https://i.imgur.com/GV528pkh.jpg' },
  { alt: 'Rock cliff', src: 'https://i.imgur.com/fDnaiDhh.jpg' },
  { alt: 'Rock cliff', src: 'https://i.imgur.com/zQ6fMGRh.jpg' },
  { alt: 'Skull graffiti', src: 'https://i.imgur.com/9D9dFFSh.jpg' },
  { alt: 'Waves crashing on rock cliff', src: 'https://i.imgur.com/XUh1o8Jh.jpg' },
  { alt: 'Rocky beach cliff', src: 'https://i.imgur.com/4PYNliTh.jpg' },
  { alt: 'Rocky formation', src: 'https://i.imgur.com/zhe5l5vh.jpg' },
];

const mammoth2020 = [
  { alt: '', src: 'https://imgur.com/1utq2yqh.jpg' },
  { alt: '', src: 'https://imgur.com/T7MjBdsh.jpg' },
  { alt: '', src: 'https://imgur.com/alDWxFVh.jpg' },
  { alt: '', src: 'https://imgur.com/gIbfArqh.jpg' },
  { alt: '', src: 'https://imgur.com/L2YfnW6h.jpg' },
  { alt: '', src: 'https://imgur.com/BwzwTJah.jpg' },
  { alt: '', src: 'https://imgur.com/AVnzEAHh.jpg' },
  { alt: '', src: 'https://imgur.com/0CrmUoBh.jpg' },
  { alt: '', src: 'https://imgur.com/aBBvxrJh.jpg' },
  { alt: '', src: 'https://imgur.com/rQATyR8h.jpg' },
  { alt: '', src: 'https://imgur.com/s4abVRKh.jpg' },
  { alt: '', src: 'https://imgur.com/WeZBTrmh.jpg' },
  { alt: '', src: 'https://imgur.com/z6bjSavh.jpg' },
  { alt: '', src: 'https://imgur.com/UQujKmfh.jpg' },
  { alt: '', src: 'https://imgur.com/hB2PoLXh.jpg' },
  { alt: '', src: 'https://imgur.com/wGR0feTh.jpg' },
  { alt: '', src: 'https://imgur.com/kUG6fphh.jpg' },
  { alt: '', src: 'https://imgur.com/3ATEcZrh.jpg' },
  { alt: '', src: 'https://imgur.com/OLuZ5uhh.jpg' },
  { alt: '', src: 'https://imgur.com/kly5MHvh.jpg' },
  { alt: '', src: 'https://imgur.com/Pjys7TMh.jpg' },
  { alt: '', src: 'https://imgur.com/uJnV23nh.jpg' },
  { alt: '', src: 'https://imgur.com/1yp51Pth.jpg' },
  { alt: '', src: 'https://imgur.com/g7HvCpEh.jpg' },
  { alt: '', src: 'https://imgur.com/s6tBbE3h.jpg' },
  { alt: '', src: 'https://imgur.com/rH3Xr3Lh.jpg' },
  { alt: '', src: 'https://imgur.com/FUowoImh.jpg' },
  { alt: '', src: 'https://imgur.com/8FYswirh.jpg' },
  { alt: '', src: 'https://imgur.com/Ey79SR4h.jpg' },
  { alt: '', src: 'https://imgur.com/OFKoE0gh.jpg' },
  { alt: '', src: 'https://imgur.com/9oTpx67h.jpg' },
  { alt: '', src: 'https://imgur.com/aBlqf1bh.jpg' },
  { alt: '', src: 'https://imgur.com/VAzKPVTh.jpg' },
  { alt: '', src: 'https://imgur.com/82YBjlhh.jpg' },
  { alt: '', src: 'https://imgur.com/zk0fPjgh.jpg' },
  { alt: '', src: 'https://imgur.com/XtxSQ7Lh.jpg' },
];

const roadtrip2018 = [
  { alt: 'Cloudy golden gate bridge', src: 'https://i.imgur.com/TIOUR0jh.jpg' },
  { alt: 'Golden gate bridge', src: 'https://i.imgur.com/F6faSNHh.jpg' },
  { alt: 'Welcome to oregon sign', src: 'https://i.imgur.com/r6M4uBSh.jpg' },
  { alt: 'No skateboarding sign', src: 'https://i.imgur.com/D51aCZYh.jpg' },
  { alt: 'Mount Rushmore', src: 'https://i.imgur.com/Oh3EccTh.jpg' },
  { alt: 'Smoke filled woods', src: 'https://i.imgur.com/P1sjmZGh.jpg' },
  { alt: 'Tree with smoke behind', src: 'https://i.imgur.com/iDD2jZRh.jpg' },
  { alt: 'Rocky beach shore', src: 'https://i.imgur.com/tkF9Tioh.jpg' },
  { alt: 'Tree stump', src: 'https://i.imgur.com/gojJX3Ch.jpg' },
  { alt: 'Red flowers on cliff', src: 'https://i.imgur.com/SoZVotmh.jpg' },
  { alt: 'Yellow plant on cliff', src: 'https://i.imgur.com/RAe8QDNh.jpg' },
  { alt: 'Seagull flying over ocean', src: 'https://i.imgur.com/teUSujUh.jpg' },
  { alt: 'Sandy beach trail', src: 'https://i.imgur.com/GRo0G5Rh.jpg' },
  { alt: 'Rocky river bed', src: 'https://i.imgur.com/2E8xqhch.jpg' },
  { alt: 'Sandy beach trail', src: 'https://i.imgur.com/X4N3X1Jh.jpg' },
  { alt: 'Sandy beach trail', src: 'https://i.imgur.com/rhnKrmJh.jpg' },
  { alt: 'Snow covered mount rainier', src: 'https://i.imgur.com/vLK0bT4h.jpg' },
  { alt: 'Rocky river bed', src: 'https://i.imgur.com/YS97q7jh.jpg' },
  { alt: 'Big redwood tree', src: 'https://i.imgur.com/ZMJ94LXh.jpg' },
  { alt: 'Badlands national park welcome sign', src: 'https://i.imgur.com/EyZ4X0Zh.jpg' },
  { alt: 'Flowers with Mount Rainier in back', src: 'https://i.imgur.com/pcPTuKFh.jpg' },
  { alt: 'Park entrance sign', src: 'https://i.imgur.com/NoRjKlqh.jpg' },
  { alt: 'Elk in field', src: 'https://i.imgur.com/q4H9zcQh.jpg' },
  { alt: 'Elk in field', src: 'https://i.imgur.com/lJU5X3rh.jpg' },
  { alt: 'Blue lake with mountains behind', src: 'https://i.imgur.com/eXJKwYeh.jpg' },
  { alt: 'Rocky beach cliff', src: 'https://i.imgur.com/gqpChVnh.jpg' },
  { alt: 'Paul bunyan statue', src: 'https://i.imgur.com/eK0DSrNh.jpg' },
  { alt: 'Sandy beach trail', src: 'https://i.imgur.com/SD4FZBfh.jpg' },
  { alt: 'Road with trees on either side', src: 'https://i.imgur.com/6qF4n5Oh.jpg' },
  { alt: 'Rocky stone bridge', src: 'https://i.imgur.com/8idmR3Nh.jpg' },
  { alt: 'Snow covered mount rainier', src: 'https://i.imgur.com/rB9gzRmh.jpg' },
  { alt: 'Rocky beach shore', src: 'https://i.imgur.com/l7Hkeaeh.jpg' },
  { alt: 'Blue lake with mountains behind', src: 'https://i.imgur.com/TbxcPLPh.jpg' },
  { alt: 'Snow covered mount rainier', src: 'https://i.imgur.com/09KiGvth.jpg' },
  { alt: 'Snow covered mount rainier', src: 'https://i.imgur.com/z0IqDWHh.jpg' },
  { alt: 'Glacier national park welcome sign', src: 'https://i.imgur.com/SkMfJ2Uh.jpg' },
  { alt: 'Blue lake with mountains behind', src: 'https://i.imgur.com/EIyHck5h.jpg' },
  { alt: 'Blue lake with mountains behind', src: 'https://i.imgur.com/wZElGBrh.jpg' },
  { alt: 'Blue lake with mountains behind', src: 'https://i.imgur.com/ZQLyDULh.jpg' },
  { alt: 'Blue lake with mountains behind', src: 'https://i.imgur.com/GzZWZiih.jpg' },
  { alt: 'Blue lake with mountains behind', src: 'https://i.imgur.com/cUsxi9Ah.jpg' },
  { alt: 'Badlands national park', src: 'https://i.imgur.com/oXTFT6Sh.jpg' },
  { alt: 'Badlands national park', src: 'https://i.imgur.com/CqzDWNqh.jpg' },
  { alt: 'Mountain goat in badlands national park', src: 'https://i.imgur.com/PjoaX88h.jpg' },
  { alt: 'Frog in river', src: 'https://i.imgur.com/7n1k0POh.jpg' },
  { alt: 'Tsunami warning sign', src: 'https://i.imgur.com/P45nT1eh.jpg' },
  { alt: 'Elk in field', src: 'https://i.imgur.com/OUlKrXKh.jpg' },
  { alt: 'Frog in river', src: 'https://i.imgur.com/NVEPX8Ph.jpg' },
];

const roadtrip2022 = [
  { src: 'https://i.imgur.com/XcN5CEVh.jpg', alt: 'Cloudy golden gate bridge' },
  { src: 'https://i.imgur.com/uCnnyoXh.jpg', alt: 'Golden gate bridge' },
  { src: 'https://i.imgur.com/0XMHXlVh.jpg', alt: 'Welcome to oregon sign' },
  { src: 'https://i.imgur.com/C5F5r4uh.jpg', alt: 'No skateboarding sign' },
  { src: 'https://i.imgur.com/seXglrPh.jpg', alt: 'Mount Rushmore' },
  { src: 'https://i.imgur.com/wQ8OpUWh.jpg', alt: 'Smoke filled woods' },
  { src: 'https://i.imgur.com/RTG597Lh.jpg', alt: 'Tree with smoke behind' },
];

const summer2017 = [
  { alt: 'Grand Canyon welcome sign', src: 'https://i.imgur.com/2nvi3DRh.jpg' },
  { alt: 'River with cliff in background', src: 'https://i.imgur.com/G5vpNWPh.jpg' },
  { alt: 'Green valley with river running through', src: 'https://i.imgur.com/mAUFQpMh.jpg' },
  { alt: 'Green valley with river running through', src: 'https://i.imgur.com/MOWhyNRh.jpg' },
  { alt: 'Trail on cliff', src: 'https://i.imgur.com/7pvL108h.jpg' },
  { alt: 'Narrow canyon', src: 'https://i.imgur.com/ufycp4Wh.jpg' },
  { alt: 'Grand canyon through tree branches', src: 'https://i.imgur.com/cPQI4ith.jpg' },
  { alt: 'Sunset over cliff', src: 'https://i.imgur.com/6cQpC4Ph.jpg' },
  { alt: 'Zion National Park welcome sign', src: 'https://i.imgur.com/xjBY8fPh.jpg' },
  { alt: 'Zion National Park welcome sign', src: 'https://i.imgur.com/6IGnobLh.jpg' },
  { alt: 'Windy road with rocks behind', src: 'https://i.imgur.com/X4Llw61h.jpg' },
  { alt: 'Valley with river running through', src: 'https://i.imgur.com/gDgFEnNh.jpg' },
  { alt: 'Trail through forest', src: 'https://i.imgur.com/z4lsdnxh.jpg' },
  { alt: 'Trail with mountain in back', src: 'https://i.imgur.com/EH4lv5Ah.jpg' },
  { alt: 'Sun setting on lone mountain peak', src: 'https://i.imgur.com/VB2jFLlh.jpg' },
  { alt: 'Intricate cobweb', src: 'https://i.imgur.com/yjeIJxbh.jpg' },
  { alt: 'Sign on bridge over cliff', src: 'https://i.imgur.com/Yzq3JE1h.jpg' },
  { alt: 'Tree branch with mountain in back', src: 'https://i.imgur.com/oGR1ncFh.jpg' },
  { alt: 'Tree branch with mountain in back', src: 'https://i.imgur.com/dbHVfrth.jpg' },
  { alt: 'Deer in forest', src: 'https://i.imgur.com/6Vc7A9lh.jpg' },
];

const tetons2021 = [
  { alt: '', src:'https://imgur.com/CBNzG0mh.jpg' },
  { alt: '', src:'https://imgur.com/oJalWGRh.jpg' },
  { alt: '', src:'https://imgur.com/NlSFUMvh.jpg' },
  { alt: '', src:'https://imgur.com/yFMF77Dh.jpg' },
  { alt: '', src:'https://imgur.com/A8d5qBeh.jpg' },
  { alt: '', src:'https://imgur.com/kEL4Mcxh.jpg' },
  { alt: '', src:'https://imgur.com/Wk02uxjh.jpg' },
  { alt: '', src:'https://imgur.com/mziP30Eh.jpg' },
  { alt: '', src:'https://imgur.com/CdOPTe2h.jpg' },
  { alt: '', src:'https://imgur.com/nwns525h.jpg' },
  { alt: '', src:'https://imgur.com/QYF3Ntsh.jpg' },
  { alt: '', src:'https://imgur.com/M7vl6CSh.jpg' },
  { alt: '', src:'https://imgur.com/REc3lBjh.jpg' },
  { alt: '', src:'https://imgur.com/5xPT6Rgh.jpg' },
  { alt: '', src:'https://imgur.com/y50ycqEh.jpg' },
  { alt: '', src:'https://imgur.com/jMEa11bh.jpg' },
  { alt: '', src:'https://imgur.com/xsn6amUh.jpg' },
  { alt: '', src:'https://imgur.com/R6i8eYqh.jpg' },
  { alt: '', src:'https://imgur.com/nsKoO8zh.jpg' },
  { alt: '', src:'https://imgur.com/XplkOcNh.jpg' },
  { alt: '', src:'https://imgur.com/gaG7kz4h.jpg' },
  { alt: '', src:'https://imgur.com/LqYj8Pwh.jpg' },
  { alt: '', src:'https://imgur.com/Nsj0dofh.jpg' },
  { alt: '', src:'https://imgur.com/BZLvEsuh.jpg' },
  { alt: '', src:'https://imgur.com/bM9HOOMh.jpg' },
  { alt: '', src:'https://imgur.com/4jLERhjh.jpg' },
  { alt: '', src:'https://imgur.com/w0OX1kYh.jpg' },
  { alt: '', src:'https://imgur.com/ZpmMweah.jpg' },
  { alt: '', src:'https://imgur.com/cnXdkC6h.jpg' },
  { alt: '', src:'https://imgur.com/7G7ZMcih.jpg' },
  { alt: '', src:'https://imgur.com/QeP0Gmqh.jpg' },
  { alt: '', src:'https://imgur.com/JZ3dvfLh.jpg' },
  { alt: '', src:'https://imgur.com/2Vj6i63h.jpg' },
  { alt: '', src:'https://imgur.com/ZOYGVQhh.jpg' },
  { alt: '', src:'https://imgur.com/4uk0NHLh.jpg' },
  { alt: '', src:'https://imgur.com/Hh78of6h.jpg' },
  { alt: '', src:'https://imgur.com/MsNxiNph.jpg' },
  { alt: '', src:'https://imgur.com/6KmGbxhh.jpg' },
];

const yellowstone2021 = [
  { alt: '', src: 'https://imgur.com/gK7Se9vh.jpg' },
  { alt: '', src: 'https://imgur.com/AvfHwJyh.jpg' },
  { alt: '', src: 'https://imgur.com/hQW8EDxh.jpg' },
  { alt: '', src: 'https://imgur.com/RIZdcvUh.jpg' },
  { alt: '', src: 'https://imgur.com/4kfQYDKh.jpg' },
  { alt: '', src: 'https://imgur.com/hPs33zZh.jpg' },
  { alt: '', src: 'https://imgur.com/pyXZg9Xh.jpg' },
  { alt: '', src: 'https://imgur.com/rdp3efXh.jpg' },
  { alt: '', src: 'https://imgur.com/zOFxlV3h.jpg' },
  { alt: '', src: 'https://imgur.com/PaZKAozh.jpg' },
  { alt: '', src: 'https://imgur.com/cQAUuDNh.jpg' },
  { alt: '', src: 'https://imgur.com/Gsf3piFh.jpg' },
  { alt: '', src: 'https://imgur.com/3NV7SR2h.jpg' },
  { alt: '', src: 'https://imgur.com/Htb3010h.jpg' },
  { alt: '', src: 'https://imgur.com/uNUojCIh.jpg' },
  { alt: '', src: 'https://imgur.com/95LzaXwh.jpg' },
  { alt: '', src: 'https://imgur.com/3vrtpDAh.jpg' },
  { alt: '', src: 'https://imgur.com/jI3j8GOh.jpg' },
  { alt: '', src: 'https://imgur.com/bP3qnP0h.jpg' },
  { alt: '', src: 'https://imgur.com/e7OfvEnh.jpg' },
  { alt: '', src: 'https://imgur.com/CgKJbZth.jpg' },
  { alt: '', src: 'https://imgur.com/bN1I5aqh.jpg' },
  { alt: '', src: 'https://imgur.com/ND1CC9hh.jpg' },
  { alt: '', src: 'https://imgur.com/D8piZcCh.jpg' },
  { alt: '', src: 'https://imgur.com/e1jm51Gh.jpg' },
  { alt: '', src: 'https://imgur.com/lEpSqiSh.jpg' },
  { alt: '', src: 'https://imgur.com/kP0LMMfh.jpg' },
  { alt: '', src: 'https://imgur.com/FWucYsNh.jpg' },
  { alt: '', src: 'https://imgur.com/M45Wnq3h.jpg' },
  { alt: '', src: 'https://imgur.com/ooWzqhOh.jpg' },
  { alt: '', src: 'https://imgur.com/Wb6KL6wh.jpg' },
  { alt: '', src: 'https://imgur.com/bap5nych.jpg' },
  { alt: '', src: 'https://imgur.com/pbbVLETh.jpg' },
  { alt: '', src: 'https://imgur.com/lM09uBGh.jpg' },
  { alt: '', src: 'https://imgur.com/6oOMd9Oh.jpg' },
  { alt: '', src: '' },
];

const yosemite2019 = [
  { alt: 'Taft point in yosemite', src: 'https://i.imgur.com/Cywm5adh.jpg' },
  { alt: 'Taft point in yosemite', src: 'https://i.imgur.com/t2Vs2qeh.jpg' },
  { alt: 'Taft point in yosemite', src: 'https://i.imgur.com/ms9FOjuh.jpg' },
  { alt: 'Taft point in yosemite', src: 'https://i.imgur.com/ATdT872h.jpg' },
  { alt: 'Taft point in yosemite', src: 'https://i.imgur.com/VfOvzxJh.jpg' },
  { alt: 'El Capitan in yosemite', src: 'https://i.imgur.com/LoN2gGHh.jpg' },
  { alt: 'El Capitan in yosemite', src: 'https://i.imgur.com/4PuAD8eh.jpg' },
  { alt: 'Taft point sign', src: 'https://i.imgur.com/0LWmDqCh.jpg' },
  { alt: 'El capitan', src: 'https://i.imgur.com/Jo7rB7hh.jpg' },
  { alt: 'Big Waterfall', src: 'https://i.imgur.com/O9DYB36h.jpg' },
  { alt: 'Fissure in a cliff', src: 'https://i.imgur.com/kiQ3CC8h.jpg' },
  { alt: 'Fallen tree in woods', src: 'https://i.imgur.com/hfbu7Ahh.jpg' },
  { alt: 'Yosemite valley', src: 'https://i.imgur.com/z5nZFAdh.jpg' },
  { alt: 'Big Waterfall', src: 'https://i.imgur.com/mVwGTVZh.jpg' },
  { alt: 'Sun shining through trees', src: 'https://i.imgur.com/KHii5Ufh.jpg' },
  { alt: 'Yosemite valley', src: 'https://i.imgur.com/ei1x4Zkh.jpg' },
  { alt: 'Redwood trees', src: 'https://i.imgur.com/FBKUdBgh.jpg' },
  { alt: 'Yosemite valley', src: 'https://i.imgur.com/ei1x4Zkh.jpg' },
  { alt: 'Waterfall in yosemite valley', src: 'https://i.imgur.com/MY0QOQXh.jpg' },
  { alt: 'Yosemite valley', src: 'https://i.imgur.com/S2IlYBbh.jpg' },
];


// PORTRAITS

const rio3m = [
  { alt: 'Mom holding infant', src: 'https://i.imgur.com/njwLK41h.jpg' },
  { alt: 'Baby smiling', src: 'https://i.imgur.com/dfNjeDmh.jpg' },
  { alt: 'Baby smiling', src: 'https://i.imgur.com/7g98dqLh.jpg' },
  { alt: 'Brother kissing little baby brother', src: 'https://i.imgur.com/R18wZ1Eh.jpg' },
  { alt: 'Brother kissing little baby brother', src: 'https://i.imgur.com/SKKqkQbh.jpg' },
  { alt: 'Two baby brothers smiling', src: 'https://i.imgur.com/2Sw6M0xh.jpg' },
  { alt: 'Baby smiling', src: 'https://i.imgur.com/IulcjxGh.jpg' },
  { alt: 'Baby smiling', src: 'https://i.imgur.com/6HOblB9h.jpg' },
  { alt: 'Uncle and toddler sitting on bridge', src: 'https://i.imgur.com/pod4DkNh.jpg' },
  { alt: 'Uncle holding toddler', src: 'https://i.imgur.com/Z8VnGj0h.jpg' },
  { alt: 'Mom holding toddler', src: 'https://i.imgur.com/27q3Ssoh.jpg' },
  { alt: 'Mom holding toddler', src: 'https://i.imgur.com/yJohYrQh.jpg' },
  { alt: 'Mom holding up infant', src: 'https://i.imgur.com/VIz4suEh.jpg' },
  { alt: 'Mom holding infant', src: 'https://i.imgur.com/OB6TrtUh.jpg' },
  { alt: 'Mom kissing infant', src: 'https://i.imgur.com/9QPkpelh.jpg' },
  { alt: 'Mom holding infant', src: 'https://i.imgur.com/3VmdEUkh.jpg' },
  { alt: 'Mom holding infant', src: 'https://i.imgur.com/BT99qxyh.jpg' },
  { alt: 'Mom holding infant', src: 'https://i.imgur.com/bFt1pA7h.jpg' },
  { alt: 'Parents holding toddler and infant', src: 'https://i.imgur.com/E9v3LAoh.jpg' },
  { alt: 'Parents holding toddler and infant', src: 'https://i.imgur.com/EhT7m7hh.jpg' },
  { alt: 'Dad kissing infant', src: 'https://i.imgur.com/WsMbYU9h.jpg' },
  { alt: 'Parents holding up infant', src: 'https://i.imgur.com/NVGhDGjh.jpg' },
  { alt: 'Parents sitting with infant', src: 'https://i.imgur.com/YxpHwV8h.jpg' },
  { alt: 'Mom holding toddler and infant', src: 'https://i.imgur.com/QwnN5ixh.jpg' },
  { alt: 'Mom holding infant', src: 'https://i.imgur.com/vejfbAUh.jpg' },
  { alt: 'Parents holding toddler and infant', src: 'https://i.imgur.com/x88FvV8h.jpg' },
  { alt: 'Parents holding toddler and infant', src: 'https://i.imgur.com/CEFhqfIh.jpg' },
  { alt: 'Parents holding toddler and infant', src: 'https://i.imgur.com/ks8ItUjh.jpg' },
  { alt: 'Parents holding toddler and infant', src: 'https://i.imgur.com/Avlv3a8h.jpg' },
  { alt: 'Parents holding toddler and infant', src: 'https://i.imgur.com/e9JN4L8h.jpg' },
  { alt: 'Mom holding infant', src: 'https://i.imgur.com/bbwFJckh.jpg' },
  { alt: 'Mom holding infant', src: 'https://i.imgur.com/zz44Lsmh.jpg' },
  { alt: 'Mom holding infant', src: 'https://i.imgur.com/D1o53dXh.jpg' },
  { alt: 'Parents kissing infant', src: 'https://i.imgur.com/fs67brTh.jpg' },
  { alt: 'Mom walking with toddler', src: 'https://i.imgur.com/0CVg5E3h.jpg' },
  { alt: 'Uncle holding infant', src: 'https://i.imgur.com/7ASuOFqh.jpg' },
  { alt: 'Uncle holding infant', src: 'https://i.imgur.com/edCFnOMh.jpg' },
  { alt: 'Uncle holding infant', src: 'https://i.imgur.com/Zks6W1Mh.jpg' },
  { alt: 'Uncle holding infant', src: 'https://i.imgur.com/dMKluWAh.jpg' },
  { alt: 'Mom holding infant', src: 'https://i.imgur.com/k1zm7QQh.jpg' },
  { alt: 'Mom holding infant', src: 'https://i.imgur.com/7kSwo2th.jpg' },
  { alt: 'Brothers lying down and smiling', src: 'https://i.imgur.com/pCM1njKh.jpg' },
  { alt: 'Brothers lying down and smiling', src: 'https://i.imgur.com/GVytVech.jpg' },
  { alt: 'Toddler kissing baby brother', src: 'https://i.imgur.com/FZFxkorh.jpg' },
  { alt: 'Toddler kissing baby brother', src: 'https://i.imgur.com/poK1L7Dh.jpg' },
  { alt: 'Toddler kissing baby brother', src: 'https://i.imgur.com/KY1dWrzh.jpg' },
  { alt: 'Toddler kissing baby brother', src: 'https://i.imgur.com/CDnsF7Zh.jpg' },
  { alt: 'Toddler lying with baby brother', src: 'https://i.imgur.com/JgHqXQEh.jpg' },
  { alt: 'Infant smiling', src: 'https://i.imgur.com/OXYgjI1h.jpg' },
  { alt: 'Infant smiling', src: 'https://i.imgur.com/EolW9Oeh.jpg' },
  { alt: 'Infant smiling', src: 'https://i.imgur.com/u8FATExh.jpg' },
  { alt: 'Grandma kissing infant', src: 'https://i.imgur.com/2pmSujUh.jpg' },
  { alt: 'Parents holding infant', src: 'https://i.imgur.com/j2s3TFqh.jpg' },
  { alt: 'Parents holding infant', src: 'https://i.imgur.com/oZVJoj9h.jpg' },
  { alt: 'Parents holding infant', src: 'https://i.imgur.com/JTwAM47h.jpg' },
  { alt: 'Parents holding infant', src: 'https://i.imgur.com/2SwqQCnh.jpg' },
  { alt: 'Grandma holding toddler and infant', src: 'https://i.imgur.com/6qPcSlEh.jpg' },
  { alt: 'Grandma holding toddler and infant', src: 'https://i.imgur.com/FxwlTrHh.jpg' },
  { alt: 'Grandma holding toddler and infant', src: 'https://i.imgur.com/eesyYpUh.jpg' },
  { alt: 'Grandma holding toddler and infant', src: 'https://i.imgur.com/KaaNChyh.jpg' },
  { alt: 'Dad holding infant', src: 'https://i.imgur.com/XRhWz5Jh.jpg' },
  { alt: 'Dad holding infant', src: 'https://i.imgur.com/87yBB45h.jpg' },
  { alt: 'Dad hugging toddler', src: 'https://i.imgur.com/8sEbNKMh.jpg' },
  { alt: 'Dad hugging toddler', src: 'https://i.imgur.com/uwrWBuph.jpg' },
  { alt: 'Mom and her son smiling', src: 'https://i.imgur.com/6HTMFRVh.jpg' },
  { alt: 'Toddler and baby brother smiling', src: 'https://i.imgur.com/la2im39h.jpg' },
  { alt: 'Toddler and baby brother smiling', src: 'https://i.imgur.com/zHZnOAWh.jpg' },
  { alt: 'Mom holding toddler and infant', src: 'https://i.imgur.com/HNhFNGfh.jpg' },
  { alt: 'Mom holding toddler and infant', src: 'https://i.imgur.com/zJFKEFHh.jpg' },
  { alt: 'Parents sitting with infant', src: 'https://i.imgur.com/u8AgMyWh.jpg' },
  { alt: 'Dad hugging toddler', src: 'https://i.imgur.com/JBWQsTbh.jpg' },
];

const rio8m = [
  { alt: 'Infant smiling', src: 'https://i.imgur.com/REfswYeh.jpg' },
  { alt: 'Toddler holding baby cousin', src: 'https://i.imgur.com/h4rSEp3h.jpg' },
  { alt: 'Mom kissing infant', src: 'https://i.imgur.com/MfqIXd0h.jpg' },
  { alt: 'Mom kissing infant', src: 'https://i.imgur.com/nnBsIuFh.jpg' },
  { alt: 'Mom holding infant', src: 'https://i.imgur.com/nALH0eBh.jpg' },
  { alt: 'Mom holding infant', src: 'https://i.imgur.com/JDCHePTh.jpg' },
  { alt: 'Mom holding toddler and infant', src: 'https://i.imgur.com/fqh3oAqh.jpg' },
  { alt: 'Mom holding toddler and infant', src: 'https://i.imgur.com/PtPI4XEh.jpg' },
  { alt: 'Mom holding toddler and infant', src: 'https://i.imgur.com/sTjyA4Qh.jpg' },
  { alt: 'Mom kissing infant', src: 'https://i.imgur.com/K08MdmVh.jpg' },
  { alt: 'Mom holding infant', src: 'https://i.imgur.com/cZQXjh8h.jpg' },
  { alt: 'Mom holding infant', src: 'https://i.imgur.com/ey8qrgkh.jpg' },
];

const rio15m = [
  { alt: '', src: 'https://imgur.com/GwO88UWh.jpg' },
  { alt: '', src: 'https://imgur.com/OrSUnSwh.jpg' },
  { alt: '', src: 'https://imgur.com/gcq0X4Dh.jpg' },
  { alt: '', src: 'https://imgur.com/iGoafgnh.jpg' },
  { alt: '', src: 'https://imgur.com/L8953DFh.jpg' },
  { alt: '', src: 'https://imgur.com/vLZDoeAh.jpg' },
  { alt: '', src: 'https://imgur.com/o6JPTEth.jpg' },
  { alt: '', src: 'https://imgur.com/6t9S7TVh.jpg' },
  { alt: '', src: 'https://imgur.com/lW54vxFh.jpg' },
  { alt: '', src: 'https://imgur.com/vQOem9wh.jpg' },
  { alt: '', src: 'https://imgur.com/5H0pyOSh.jpg' },
  { alt: '', src: 'https://imgur.com/LP1BIwSh.jpg' },
  { alt: '', src: 'https://imgur.com/w8DBBPdh.jpg' },
  { alt: '', src: 'https://imgur.com/dsYrxgch.jpg' },
  { alt: '', src: 'https://imgur.com/FTRP2QQh.jpg' },
  { alt: '', src: 'https://imgur.com/GSaW0ash.jpg' },
  { alt: '', src: 'https://imgur.com/MpA1myah.jpg' },
  { alt: '', src: 'https://imgur.com/OZLfZU7h.jpg' },
  { alt: '', src: 'https://imgur.com/Jx4lfNqh.jpg' },
  { alt: '', src: 'https://imgur.com/2SkIM1Vh.jpg' },
  { alt: '', src: 'https://imgur.com/xKO3Z1Lh.jpg' },
  { alt: '', src: 'https://imgur.com/daCkMuUh.jpg' },
  { alt: '', src: 'https://imgur.com/UWtMnRwh.jpg' },
  { alt: '', src: 'https://imgur.com/A1IH2sRh.jpg' },
  { alt: '', src: 'https://imgur.com/r5xRFyqh.jpg' },
  { alt: '', src: 'https://imgur.com/3lqJpKvh.jpg' },
  { alt: '', src: 'https://imgur.com/0N6uDf7h.jpg' },
  { alt: '', src: 'https://imgur.com/5mfP2T9h.jpg' },
  { alt: '', src: 'https://imgur.com/AvYjq1bh.jpg' },
  { alt: '', src: 'https://imgur.com/CbsioSBh.jpg' },
  { alt: '', src: 'https://imgur.com/IfE8zuCh.jpg' },
  { alt: '', src: 'https://imgur.com/r2XQoseh.jpg' },
  { alt: '', src: 'https://imgur.com/any9TxBh.jpg' },
  { alt: '', src: 'https://imgur.com/CY67Mqsh.jpg' },
  { alt: '', src: 'https://imgur.com/UULruq4h.jpg' },
  { alt: '', src: 'https://imgur.com/h0Mn2Elh.jpg' },
  { alt: '', src: 'https://imgur.com/3CzdKeIh.jpg' },
  { alt: '', src: 'https://imgur.com/RJlNtJbh.jpg' },
  { alt: '', src: 'https://imgur.com/JmXJrDSh.jpg' },
  { alt: '', src: 'https://imgur.com/8XG9HJCh.jpg' },
  { alt: '', src: 'https://imgur.com/2DkrRzVh.jpg' },
  { alt: '', src: 'https://imgur.com/kjIqdXCh.jpg' },
  { alt: '', src: 'https://imgur.com/smBRSPch.jpg' },
  { alt: '', src: 'https://imgur.com/UbV4JtXh.jpg' },
  { alt: '', src: 'https://imgur.com/oIG7eYih.jpg' },
  { alt: '', src: 'https://imgur.com/WVQqHoah.jpg' },
  { alt: '', src: 'https://imgur.com/yi6jQhkh.jpg' },
  { alt: '', src: 'https://imgur.com/8GvTL4Ah.jpg' },
  { alt: '', src: 'https://imgur.com/ly2BD3Hh.jpg' },
  { alt: '', src: 'https://imgur.com/kwIhTVTh.jpg' },
  { alt: '', src: 'https://imgur.com/OQuYVezh.jpg' },
  { alt: '', src: 'https://imgur.com/lFz7rmPh.jpg' },
  { alt: '', src: 'https://imgur.com/qcp6H0Ph.jpg' },
  { alt: '', src: 'https://imgur.com/g9rbm0ih.jpg' },
  { alt: '', src: 'https://imgur.com/FsiyEK9h.jpg' },
  { alt: '', src: 'https://imgur.com/yRZyWnqh.jpg' },
  { alt: '', src: 'https://imgur.com/jjtxDlqh.jpg' },
  { alt: '', src: 'https://imgur.com/GWdRwM6h.jpg' },
  { alt: '', src: 'https://imgur.com/Cs2COLHh.jpg' },
];

const teddy12m = [
  { alt: 'Mom holding baby', src: 'https://i.imgur.com/IdjwIUfh.jpg' },
  { alt: 'Mom holding up baby', src: 'https://i.imgur.com/RCyLK6mh.jpg' },
  { alt: 'Parents holding toddler', src: 'https://i.imgur.com/EuJinXYh.jpg' },
  { alt: 'Baby standing in front of tent', src: 'https://i.imgur.com/WXDMAtYh.jpg' },
  { alt: 'Mom kissing baby', src: 'https://i.imgur.com/kX37vYkh.jpg' },
  { alt: 'Mom kissing baby', src: 'https://i.imgur.com/hOWB0MPh.jpg' },
  { alt: 'Mom holding up baby', src: 'https://i.imgur.com/zGivwcNh.jpg' },
  { alt: 'Mom holding baby upside down', src: 'https://i.imgur.com/WlYNlRxh.jpg' },
  { alt: 'Baby sitting in tent', src: 'https://i.imgur.com/s0H7d46h.jpg' },
  { alt: 'Baby sitting in tent', src: 'https://i.imgur.com/SXA1vj6h.jpg' },
  { alt: 'Mom holding baby by tree', src: 'https://i.imgur.com/cb660jwh.jpg' },
  { alt: 'Mom looking at baby', src: 'https://i.imgur.com/WMMnvkmh.jpg' },
  { alt: 'Baby in yellow raincoat', src: 'https://i.imgur.com/fNHGVPDh.jpg' },
  { alt: 'Baby in yellow raincoat', src: 'https://i.imgur.com/qLoKXCTh.jpg' },
  { alt: 'Baby in yellow raincoat', src: 'https://i.imgur.com/QtFKVnth.jpg' },
  { alt: 'Baby in yellow raincoat', src: 'https://i.imgur.com/CLnUmnuh.jpg' },
  { alt: 'Mom looking at baby', src: 'https://i.imgur.com/rFGTCn5h.jpg' },
  { alt: 'Baby in yellow raincoat', src: 'https://i.imgur.com/Gf9PV8Fh.jpgg' },
  { alt: 'Mom holding baby in hat', src: 'https://i.imgur.com/QZeSTdZh.jpg' },
  { alt: 'Mom kissing baby in hat', src: 'https://i.imgur.com/GaeRBY8h.jpg' },
  { alt: 'Mom holding baby in hat', src: 'https://i.imgur.com/cHKzPIjh.jpg' },
  { alt: 'Baby standing on grass', src: 'https://i.imgur.com/XEFEtjSh.jpg' },
  { alt: 'Baby standing on grass', src: 'https://i.imgur.com/qDVRvdvh.jpg' },
  { alt: 'Mom holding baby', src: 'https://i.imgur.com/GcjM1wRh.jpg' },
  { alt: 'Baby standing on grass', src: 'https://i.imgur.com/qgkD30Bh.jpg' },
  { alt: 'Baby in pajamas', src: 'https://i.imgur.com/uMR1nf8h.jpg' },
  { alt: 'Mom holding two babies', src: 'https://i.imgur.com/niaFfpGh.jpg' },
];

const teddy18m = [
  { alt: 'Parents holding toddler', src: 'https://i.imgur.com/GTHUQ2Fh.jpg' },
  { alt: 'Parents kissing toddler', src: 'https://i.imgur.com/ESr2U1ah.jpg' },
  { alt: 'Parents holding toddler', src: 'https://i.imgur.com/i4jE9J7h.jpg' },
  { alt: 'Parents holding toddler', src: 'https://i.imgur.com/4yFh3k5h.jpg' },
  { alt: 'Parents swinging toddler', src: 'https://i.imgur.com/yIqSl6jh.jpg' },
  { alt: "Parents holding toddler's hands", src: 'https://i.imgur.com/UguPUrsh.jpg' },
  { alt: 'Toddler exploring', src: 'https://i.imgur.com/bp2fv6gh.jpg' },
  { alt: 'Dad holding toddler', src: 'https://i.imgur.com/dk7Qpuwh.jpg' },
  { alt: "Toddler on dad's shoudlers", src: 'https://i.imgur.com/A5wttfCh.jpg' },
  { alt: 'Mom holding toddler', src: 'https://i.imgur.com/4nk6Kwuh.jpg' },
  { alt: 'Mom holding toddler', src: 'https://i.imgur.com/dgioYpBh.jpg' },
  { alt: 'Mom kissing toddler', src: 'https://i.imgur.com/0MjuuS9h.jpg' },
  { alt: "Mom holding toddler's hand", src: 'https://i.imgur.com/zx60u6Dh.jpg' },
  { alt: "Mom holding toddler's hand", src: 'https://i.imgur.com/EycFMjah.jpg' },
  { alt: "Mom holding toddler's hand", src: 'https://i.imgur.com/TewWcFUh.jpg' },
  { alt: 'Dad holding toddler', src: 'https://i.imgur.com/YEM55fYh.jpg' },
  { alt: 'Dad holding toddler', src: 'https://i.imgur.com/HPHcxGph.jpg' },
  { alt: "Dad holding toddler's hand", src: 'https://i.imgur.com/1UZSRWah.jpg' },
  { alt: 'Toddler smiling', src: 'https://i.imgur.com/nUUXwmZh.jpg' },
  { alt: 'Toddler smiling', src: 'https://i.imgur.com/2SsjSGoh.jpg' },
  { alt: 'Toddler smiling', src: 'https://i.imgur.com/ycm6Rtnh.jpg' },
  { alt: 'Toddler smiling', src: 'https://i.imgur.com/3GAF8alh.jpg' },
  { alt: 'Toddler with teddy bear', src: 'https://i.imgur.com/YXiTtWLh.jpg' },
  { alt: 'Toddler sitting in tree', src: 'https://i.imgur.com/WfzTOvch.jpg' },
  { alt: 'Dad following toddler', src: 'https://i.imgur.com/DoaF4Zjh.jpg' },
  { alt: 'Toddler smiling', src: 'https://i.imgur.com/qp91LySh.jpg' },
  { alt: 'Dad holding toddler', src: 'https://i.imgur.com/HSC2Uh3h.jpg' },
  { alt: 'Parents holding toddler', src: 'https://i.imgur.com/d0oBQE2h.jpg' },
  { alt: 'Mom holding toddler', src: 'https://i.imgur.com/uxtQa62h.jpg' },
  { alt: 'Parents with toddler', src: 'https://i.imgur.com/z93M7eMh.jpg' },
  { alt: 'Toddler squeezing through parents legs', src: 'https://i.imgur.com/rYvGb5dh.jpg' },
  { alt: 'Parents with toddler', src: 'https://i.imgur.com/vCTbcmeh.jpg' },
  { alt: 'Toddler with stick', src: 'https://i.imgur.com/V6LhEmvh.jpg' },
  { alt: 'Parents looking at toddler', src: 'https://i.imgur.com/Y6yb5nSh.jpg' },
  { alt: 'Parents behind toddler', src: 'https://i.imgur.com/S5FWDxeh.jpg' },
  { alt: 'Toddler smiling', src: 'https://i.imgur.com/YVYmdMQh.jpg' },
  { alt: 'Mom holding toddler by tree', src: 'https://i.imgur.com/3urz12Uh.jpg' },
  { alt: 'Mom holding toddler', src: 'https://i.imgur.com/9gB4hlXh.jpg' },
  { alt: 'Mom holding toddler', src: 'https://i.imgur.com/XX6iuGWh.jpg' },
  { alt: 'Mom holding toddler', src: 'https://i.imgur.com/qW5bCoYh.jpg' },
  { alt: 'Mom kissing toddler', src: 'https://i.imgur.com/k6Yk4mmh.jpg' },
];

const trudybeachmaternity = [
  { alt: 'Parents and baby walking on beach', src: 'https://i.imgur.com/fYtIgUXh.jpg' },
  { alt: 'Pregnant mom on the beach', src: 'https://i.imgur.com/GmqwPbkh.jpg' },
  { alt: 'Pregnant mom on the beach', src: 'https://i.imgur.com/TgssZAMh.jpg' },
  { alt: 'Parents hugging on the beach', src: 'https://i.imgur.com/SZAdXFLh.jpg' },
  { alt: 'Parents hugging on the beach', src: 'https://i.imgur.com/idgVVWLh.jpg' },
  { alt: 'Parents holding toddler on the beach', src: 'https://i.imgur.com/JnujVBEh.jpg' },
  { alt: 'Dad kissing mom on the beach', src: 'https://i.imgur.com/quhexvSh.jpg' },
  { alt: 'Parents holding toddler on the beach', src: 'https://i.imgur.com/okTYbK3h.jpg' },
  { alt: 'Parents holding toddler on the beach', src: 'https://i.imgur.com/DYyMGq7h.jpg' },
  { alt: 'Dad holding toddler on the beach', src: 'https://i.imgur.com/upwPWVzh.jpg' },
  { alt: 'Pregnant mom on the beach', src: 'https://i.imgur.com/Xb9FAY3h.jpg' },
  { alt: 'Parents holding hands on the beach', src: 'https://i.imgur.com/zyR3x4eh.jpg' },
  { alt: 'Pregnant mom on the beach', src: 'https://i.imgur.com/6PahWsBh.jpg' },
  { alt: 'Pregnant mom on the beach', src: 'https://i.imgur.com/4iC88eHh.jpg' },
  { alt: 'Dad chasing toddler on the beach', src: 'https://i.imgur.com/JSI8ijkh.jpg' },
  { alt: 'Dad chasing toddler on the beach', src: 'https://i.imgur.com/OJq0QCwh.jpg' },
  { alt: 'Parents holding toddler on the beach', src: 'https://i.imgur.com/nHlcVqrh.jpg' },
  { alt: 'Parents holding toddler on the beach', src: 'https://i.imgur.com/rfwSSd8.jpg9' },
  { alt: 'Parents holding toddler on the beach', src: 'https://i.imgur.com/twfHs6kh.jpg' },
  { alt: 'Parents holding toddler on the beach', src: 'https://i.imgur.com/PH8wR4Ch.jpg' },
  { alt: 'Parents holding toddler on the beach', src: 'https://i.imgur.com/NKqQ7ANh.jpg' },
  { alt: 'Parents holding toddler on the beach', src: 'https://i.imgur.com/Teqqexgh.jpg' },
  { alt: 'Parents holding toddler on the beach', src: 'https://i.imgur.com/FCjw1lvh.jpg' },
  { alt: 'Parents holding toddler on the beach', src: 'https://i.imgur.com/Dc1MHtXh.jpg' },
  { alt: 'Parents holding toddler on the beach', src: 'https://i.imgur.com/0QQKG6xh.jpg' },
  { alt: 'Toddler walking on the beach', src: 'https://i.imgur.com/ZzMrUtwh.jpg' },
  { alt: 'Dad holding toddler on the beach', src: 'https://i.imgur.com/jYHg6LAh.jpg' },
  { alt: 'Dad holding toddler on the beach', src: 'https://i.imgur.com/63IOYNWh.jpg' },
  { alt: 'Dad holding toddler on the beach', src: 'https://i.imgur.com/YfW5GABh.jpg' },
  { alt: 'Parents holding toddler on the beach', src: 'https://i.imgur.com/dFh0xo9h.jpg' },
  { alt: 'Parents holding toddler on the beach', src: 'https://i.imgur.com/S49lw2wh.jpg' },
  { alt: 'Dad holding toddler on the beach', src: 'https://i.imgur.com/Nu2eCb8h.jpg' },
  { alt: 'Mom holding toddler on the beach', src: 'https://i.imgur.com/37Sp3I7h.jpg' },
  { alt: 'Mom holding toddler on the beach', src: 'https://i.imgur.com/yYtUTMwh.jpg' },
  { alt: 'Mom holding toddler on the beach', src: 'https://i.imgur.com/XubP81Dh.jpg' },
  { alt: 'Mom holding toddler on the beach', src: 'https://i.imgur.com/eEvZDnXh.jpg' },
  { alt: 'Mom holding toddler on the beach', src: 'https://i.imgur.com/p3nZXnAh.jpg' },
  { alt: 'Mom holding toddler on the beach', src: 'https://i.imgur.com/1CP6noQh.jpg' },
  { alt: 'Toddler on the beach', src: 'https://i.imgur.com/7PEw5mEh.jpg' },
  { alt: 'Toddler on the beach', src: 'https://i.imgur.com/z4A2pUXh.jpg' },
  { alt: 'Toddler on the beach', src: 'https://i.imgur.com/bl2VtnDh.jpg' },
  { alt: 'Dad chasing toddler on the beach', src: 'https://i.imgur.com/MWh7vMzh.jpg' },
];

const trudysnowmaternity = [
  { alt: 'Pregnant mom in the woods', src: 'https://i.imgur.com/GXljzuEh.jpg' },
  { alt: 'Pregnant mom in the woods', src: 'https://i.imgur.com/SQEmH18h.jpg' },
  { alt: 'Pregnant mom in the woods', src: 'https://i.imgur.com/3rqzh3Oh.jpg' },
  { alt: 'Mom with two toddlers', src: 'https://i.imgur.com/8gFA5Bqh.jpg' },
  { alt: 'Mom with two toddlers', src: 'https://i.imgur.com/CsybYDGh.jpg' },
  { alt: 'Mom with two toddlers', src: 'https://i.imgur.com/IKj0TkOh.jpg' },
  { alt: 'Mom with two toddlers', src: 'https://i.imgur.com/rG5Vcnoh.jpg' },
  { alt: 'Mom with two toddlers', src: 'https://i.imgur.com/dB5xg4Mh.jpg' },
  { alt: 'Mom with two toddlers', src: 'https://i.imgur.com/zMUkCn4h.jpg' },
  { alt: 'Mom with two toddlers', src: 'https://i.imgur.com/nJAqTswh.jpg' },
  { alt: 'Mom with two toddlers', src: 'https://i.imgur.com/BQWBCsRh.jpg' },
  { alt: 'Mom with two toddlers', src: 'https://i.imgur.com/q8eVBCAh.jpg' },
  { alt: 'Mom with two toddlers', src: 'https://i.imgur.com/oJW4FEbh.jpg' },
  { alt: 'Pregnant mom in the woods', src: 'https://i.imgur.com/40AO6iVh.jpg' },
  { alt: 'Mom with two toddlers', src: 'https://i.imgur.com/Sfvc8Teh.jpg' },
  { alt: 'Mom with two toddlers', src: 'https://i.imgur.com/sm9Llzzh.jpg' },
  { alt: 'Mom with two toddlers', src: 'https://i.imgur.com/vIIKX8mh.jpg' },
  { alt: 'Mom with two toddlers', src: 'https://i.imgur.com/oKf4bEyh.jpg' },
  { alt: 'Mom with two toddlers', src: 'https://i.imgur.com/fiNDU89h.jpg' },
  { alt: 'Mom with two toddlers', src: 'https://i.imgur.com/UsbV5nuh.jpg' },
  { alt: 'Mom hugging toddler', src: 'https://i.imgur.com/T5ro9U3h.jpg' },
  { alt: 'Toddler kissing mom', src: 'https://i.imgur.com/SYQS1UYh.jpg' },
  { alt: 'Pregnant mom holding toddler', src: 'https://i.imgur.com/sY2uJbJh.jpg' },
  { alt: 'Pregnant mom holding toddler', src: 'https://i.imgur.com/jmSxVAph.jpg' },
  { alt: 'Mom holding toddler and two girls', src: 'https://i.imgur.com/WS8cjOeh.jpg' },
  { alt: 'Pregnant mom holding toddler', src: 'https://i.imgur.com/vHLZLvgh.jpg' },
  { alt: 'Pregnant mom holding toddler', src: 'https://i.imgur.com/7oL59pQh.jpg' },
  { alt: 'Pregnant mom holding toddler', src: 'https://i.imgur.com/X8vHyOnh.jpg' },
  { alt: 'Pregnant mom holding toddler', src: 'https://i.imgur.com/AjTONCGh.jpg' },
  { alt: 'Pregnant mom holding toddler', src: 'https://i.imgur.com/jki1PaEh.jpg' },
  { alt: 'Mom holding toddler and two girls', src: 'https://i.imgur.com/l7w029Jh.jpg' },
  { alt: 'Pregnant mom holding toddler', src: 'https://i.imgur.com/h9patZ0h.jpg' },
  { alt: 'Pregnant mom holding toddler', src: 'https://i.imgur.com/CprfScdh.jpg' },
  { alt: 'Pregnant mom holding toddler', src: 'https://i.imgur.com/3WtL35dh.jpg' },
  { alt: 'Pregnant mom holding toddler', src: 'https://i.imgur.com/eRllQGSh.jpg' },
  { alt: 'Mom holding toddler and two girls', src: 'https://i.imgur.com/K6Apuh1h.jpg' },
  { alt: 'Pregnant mom holding toddler', src: 'https://i.imgur.com/OFTRkWdh.jpg' },
  { alt: 'Pregnant mom holding toddler', src: 'https://i.imgur.com/CRI1z50h.jpg' },
  { alt: 'Grandma and pregnant mom holding toddler', src: 'https://i.imgur.com/QxPRtE2h.jpg' },
  { alt: 'Grandma and pregnant mom holding toddler', src: 'https://i.imgur.com/SxRIVZRh.jpg' },
  { alt: 'Grandma and pregnant mom holding toddler', src: 'https://i.imgur.com/NoSDhHUh.jpg' },
  { alt: 'Mom and pregnant daughter hugging', src: 'https://i.imgur.com/IGatk16h.jpg' },
];

// ANIMALS

const animals = [
  { alt: '', src: 'https://i.imgur.com/AvfHwJyh.jpg' },
  { alt: '', src: 'https://i.imgur.com/pyXZg9Xh.jpg' },
  { alt: '', src: 'https://i.imgur.com/3NV7SR2h.jpg' },
  { alt: '', src: 'https://i.imgur.com/4jLERhjh.jpg' },
  { alt: '', src: 'https://i.imgur.com/w0OX1kYh.jpg' },
  { alt: '', src: 'https://i.imgur.com/kEL4Mcxh.jpg' },
  { alt: 'Elk in field', src: 'https://i.imgur.com/lJU5X3rh.jpg' },
  { alt: '', src: 'https://i.imgur.com/hPs33zZh.jpg' },
  { alt: 'Elk in field', src: 'https://i.imgur.com/OUlKrXKh.jpg' },
  { alt: '', src: 'https://i.imgur.com/pwhOCVCh.jpg' },
  { alt: '', src: 'https://i.imgur.com/6oOMd9Oh.jpg' },
  { alt: '', src: 'https://i.imgur.com/82YBjlhh.jpg' },
  { alt: '', src: 'https://i.imgur.com/8FRtHbEh.jpg' },
  { alt: 'Mountain goat', src: 'https://i.imgur.com/Jr6EDbSh.jpg' },
  { alt: 'Frog in river', src: 'https://i.imgur.com/NVEPX8Ph.jpg' },
  { alt: 'Mountain goat', src: 'https://i.imgur.com/Wsi7zLZh.jpg' },
  { alt: 'Mountain goat', src: 'https://i.imgur.com/Q4TpkI5h.jpg' },
  { alt: '', src: 'https://i.imgur.com/MsNxiNph.jpg' },
  { alt: 'Frog in river', src: 'https://i.imgur.com/7n1k0POh.jpg' },
  { alt: 'Bearded dragon', src: 'https://i.imgur.com/jmGH6Kqh.jpg' },
  { alt: 'Bearded dragon', src: 'https://i.imgur.com/S0Xw5mch.jpg' },
  { alt: 'Hawk in sky', src: 'https://i.imgur.com/pRCGr7Wh.jpg' },
  { alt: 'Seagull over ocean', src: 'https://i.imgur.com/teUSujUh.jpg' },
  { alt: '', src: 'https://i.imgur.com/Ey79SR4h.jpg' },
];

// MISCELLANEOUS

const misc = [
  { alt: '', src: 'https://i.imgur.com/yjeIJxbh.jpg' },
  { alt: 'Boston skyline', src: 'https://i.imgur.com/FcaDpuvh.jpg' },
  { alt: 'Band performing', src: 'https://i.imgur.com/zW9U6cHh.jpg' },
  { alt: 'Audience cheering at concert', src: 'https://i.imgur.com/u7vZcPLh.jpg' },
  { alt: 'Old plane in field', src: 'https://i.imgur.com/TTnJL0ih.jpg' },
  { alt: '', src: 'https://imgur.com/UTwAaa2h.jpg' },
  { alt: '', src: 'https://imgur.com/tYSLAdTh.jpg' },
  { alt: '', src: 'https://imgur.com/OTH2KDph.jpg' },
  { alt: '', src: 'https://imgur.com/u4ZUXlGh.jpg' },
];

export const photographs: Record<string, Array<Photograph>> = {
  alaska2018,
  alaska2020,
  animals,
  malabar2019,
  mammoth2020,
  misc,
  rio15m,
  rio3m,
  rio8m,
  roadtrip2018,
  roadtrip2022,
  summer2017,
  teddy12m,
  teddy18m,
  tetons2021,
  trudybeachmaternity,
  trudysnowmaternity,
  yellowstone2021,
  yosemite2019,
};
